name: far_nlp
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- chardet=3.0.2=py36_1
- cycler=0.10.0=py36_0
- cymem=1.31.2=py36_0
- cytoolz=0.8.2=py36_0
- dbus=1.10.10=3
- decorator=4.1.2=py36_0
- dill=0.2.6=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.1=0
- freetype=2.7=1
- ftfy=4.4.2=py36_0
- html5lib=0.999999999=py36_0
- icu=58.1=1
- idna=2.5=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.9.5=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libgfortran=3.0.0=0
- libpng=1.6.28=0
- libsodium=1.0.10=0
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=py36_1
- mistune=0.7.4=py36_0
- murmurhash=0.26.4=py36_0
- nbformat=4.3.0=py36_0
- ncurses=5.9=10
- nose=1.3.7=py36_2
- notebook=5.0.0=py36_0
- numpy=1.12.1=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- patsy=0.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.3=py36_0
- pip=9.0.1=py36_0
- preshed=1.0.0=py36_0
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_2
- qt=5.6.2=1
- qtconsole=4.3.0=py36_0
- readline=6.2=0
- regex=2017.06.23=py36_0
- requests=2.18.2=py36_0
- scikit-learn=0.18.2=np112py36_blas_openblas_200
- scipy=0.19.1=py36_blas_openblas_201
- seaborn=0.8.0=py36_0
- setuptools=36.2.2=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- spacy=1.9.0=np112py36_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=np112py36_0
- termcolor=1.1.0=py36_1
- terminado=0.6=py36_0
- thinc=6.5.2=np112py36_0
- tk=8.5.19=2
- toolz=0.8.2=py36_0
- tornado=4.5.1=py36_0
- tqdm=4.15.0=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.21.1=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- wrapt=1.10.8=py36_0
- xz=5.2.2=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- mkl=2017.0.3=0
- nbconvert=4.2.0=py36_0
- plac=0.9.6=py36_0
- ujson=1.35=py36_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - pathlib==1.0.1
  - prompt-toolkit==1.0.14
  - py==1.4.34
  - pytest==3.2.0

